### ISSUE TITLE
Warning about password property

### ISSUE THREAD

**Issue by brentleyjones** [dhoer/chef-macosx_autologin#3]
```
WARN: /var/chef/cache/cookbooks/macosx_autologin/providers/default.rb:20:in `block (2 levels) in class_from_file': property password is declared in both execute[enable automatic login] and #<#<Class:0x007fe0ef176f10>:0x007fe0f11119d8>. Use new_resource.password instead. At /var/chef/cache/cookbooks/macosx_autologin/providers/default.rb:20:in `block (2 levels) in class_from_file'
```

**Comment by dhoer** [comment]
I think that is a false positive.  I think it is ok to ignore it.  It popped up when I had to rename sensitive attribute to confidential to comply with chef 13.
